#!/bin/sh

##
# File: ruclpa - "RUn"+"CLean"+"PAck"
# Author: Andreas (add) Wilfer
#
# Authors comment:
# Yes, I know it's a horrible mess but it was
# absolutely worth the experience, having made it!
#
# About script:
# It runs somewhat like a makefile (but without some of make's features),
# it checks if the file exists, runs, cleans it up, or packages it into a
# love file if necessary, in case there already is a .love file it will
# update the already existing one.
##


file="loveRPG.love"
objects="main.lua
	tilemap.lua
	objects.lua
	tilemap.lua
	maps"


option=${1}

loveit() {
    zip -9 -r $file $objects
    echo "I was made for loving you..."
}

case ${option} in
    -r)	if [ -e $file ]
	then
	    echo "$file is there. Running!"
	    love $file
	    exit 0
	else
	    echo "$file was not there: Loving it!"
	    loveit
	    echo "$file is there now: Running!"
	    love $file
	    exit 0
	fi
	;;
    -p) loveit
	;;
    -c)	if [ -e $file ]
	then
	    rm $file
	    echo "Now it's no longer there."
	    exit 0
	else
	    echo "`basename ${0}`: Cannot clean: No $file left."
	    exit 0
	fi
	;;
    *) echo "`basename ${0}`:usage [-r - run] | [-c - clean] | [-p pack ]"
       exit 0
       ;;
esac
